id: P010635
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD19333
  title: “Субащид”-ьн་монгол་орчуулгуудьын་галиг་угсийи་хэлээ
  author: ''
  volumes:
    f39a213647c5497fb3cba45874dd6e61:
      image_group_id: I4PD4787
      title: ''
      volume_number: 1
      total_pages: 734
      base_file: v001.txt
