id: IC46B0EE8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:46:37+00:00'
last_modified: '2022-06-08T16:24:19.613369+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19333
  title: “Субащид”-ьн་монгол་орчуулгуудьын་галиг་угсийи་хэлээ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    64C6:
      image_group_id: I4PD4787
      title: ''
      total_pages: 734
      order: 1
      base_file: 64C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
